apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-practice
spec:
  type: LoadBalancer
  selector:
    app: example-practice
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
